apiVersion: v1
kind: ConfigMap
metadata:
  name: gf-grpc-template-configmap
data:
  config.yaml: |
    server:
      address: ":8000"
      openapiPath: "/api.json"
      swaggerPath: "/swagger"

    logger:
      level: "all"
      stdout: true
