# GRPC Server.
grpc:
  address: "127.0.0.1:8000"
  name: "gf-grpc-template"
  logPath: ""
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "pgsql:postgres:postgres@tcp(localhost:5432)/test"
    debug: true

